### ISSUE TITLE
Add support for testing only certain tags

### ISSUE THREAD

**Issue by reece** [biocommons/biocommons.example#17]
See https://github.com/reece/pytest-optional-tests for background

**Comment by ecalifornica** [comment]
Goals:

- [ ] Marker for network tests.
  - [ ] HTTP: Does `@pytest.mark.vcr` satisfy this?
  - [ ] PSQL: Does mocking the client responses or running a local containerized Postgres obviate the need to mark database query tests?
- [ ] Marker for smoke tests. Test suite should take no more than fifteen seconds, to be run frequently during local development. Does `@pytest.mark.quick` satisfy this?
- [ ] Documentation:
  - [ ] A short description of each marker in the `pytest` configuration, to be displayed by `pytest --markers`. I could use help deciphering the current `hgvs` markers.
  - [ ] A section in the developer documentation regarding the test marker rubric, and how to use them.
- [ ] Makefile updates?


Regarding our question today about mark exclusivity, it seems that the default is to run all tests, regardless of markers (`$ pytest`).
To run only tests marked `quick`: `$ pytest -m quick`
To run all tests, except tests marked `quick`: `$ pytest -m "not quick"`
From: https://docs.pytest.org/en/7.1.x/example/markers.html


Current `hgvs` markers:
```
@pytest.mark.extra:

@pytest.mark.issues:

@pytest.mark.mapping:

@pytest.mark.models:

@pytest.mark.normalization:

@pytest.mark.quick:

@pytest.mark.regression:

@pytest.mark.validation:

@pytest.mark.no_cover: disable coverage for this test.

@pytest.mark.anyio: mark the (coroutine function) test to be run asynchronously via anyio.

@pytest.mark.vcr: Mark the test as using VCR.py.

@pytest.mark.block_network: Block network access except for VCR recording.

@pytest.mark.default_cassette: Override the default cassette name.

@pytest.mark.allowed_hosts: List of regexes to match hosts to where connection must be allowed.
```

**Comment by reece** [comment]
(Thinking... not forgotten)

**Comment by reece** [comment]
This issue was closed by stalebot. It has been reopened to give more time for community review.  See [biocommons coding guidelines](https://biocommons.org/contributing/coding-guidelines/) for stale issue and pull request policies.  This resurrection is expected to be a onos.environ["GITHUB_TOKEN"]e-time event.
