### ISSUE TITLE
add ruff support

### ISSUE THREAD

**Issue by reece** [biocommons/biocommons.example#3]
See https://beta.ruff.rs/docs/configuration/

Decision at 2024-05-20 maintainers' meeting:
- adopt ruff
- drop pylint, pylint, isort, black
- keep pyright as-is for now
- Do the above in this repo initially, then propagate as separate issues
- for now, separate ruff check and ruff format operations

**Comment by reece** [comment]
@ecalifornica : Seems like something that you'd be interested in

**Comment by ecalifornica** [comment]
Do we want to add this to the Makefile/PR checks?

**Comment by jsstevenson** [comment]
Would like to bump this for consideration (@reece, @korikuzma, others). We're now using Ruff in virtually all of our projects as the single source of linting and formatting, and I think we're pretty happy with it -- it's fast, easy to use, centrally configurable, and offers a [wide array of available rules](https://docs.astral.sh/ruff/rules/#pycodestyle-e-w). I'm confident that it could replace virtually every linting check currently listed in pyproject.toml/.flake8 in this repo (I don't believe Ruff has complete coverage of every Pylint rule, but it's got a whole lot of them).

So, my proposal would be to go a bit further than #36 and either trim or remove entirely the other included linters/formatters.

**Comment by korikuzma** [comment]
@jsstevenson I like using ruff and would be fine only using it as our sole linter/formatter.

**Comment by jsstevenson** [comment]
One other observation: the biocommons.org dev guide says that code style is enforced with `black`, `isort`, and `pylint`. However, the template also checks with `flake8` in GitHub Actions and via pre-commit, but doesn't perform `pylint` checks in either case (although it is included as a dev dependency). It might be good to clean this up in one direction or another.

**Comment by korikuzma** [comment]
@biocommons/maintainers have decided on dropping isort, pylint, and black in favor of ruff
