### ISSUE TITLE
add support for code coverage tracking

### ISSUE THREAD

**Issue by reece** [biocommons/biocommons.example#9]
e.g., https://about.codecov.io/blog/python-code-coverage-using-github-actions-and-codecov/

**Comment by dylan-myome** [comment]
I can grab this, please expect an access request from codecov.io 
<img width="511" alt="image" src="https://github.com/biocommons/biocommons.example/assets/115101601/fdc02755-5ed6-4707-bd36-32c56b3c05b4">
